version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/unnested"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/unnested/example"
    schedule:
      interval: weekly
