name: unnested
version: 1.0.0-dev.0
description: >
  The easy way to unnest even the most complicated of widget trees.
homepage: https://github.com/GregoryConrad/unnested
repository: https://github.com/GregoryConrad/unnested
issue_tracker: https://github.com/GregoryConrad/unnested/issues
# screenshots:
#   - description: 'This screenshot shows a stack trace returning a human-readable
#   representation.'
#     path: path/to/image/in/package.png

# TODO update for Dart 3 and future Flutter version
environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.0.0-dev.0

# TODO remove this once dependency conflict is resolved
dependency_overrides:
  path: 1.8.3
