name: unnested
version: 1.0.0-dev.5
description: >
  The easy way to unnest even the most complicated of widget trees.
homepage: https://github.com/GregoryConrad/unnested
repository: https://github.com/GregoryConrad/unnested
issue_tracker: https://github.com/GregoryConrad/unnested/issues
screenshots:
  - path: assets/banner.png
    description: >
      This screenshot shows the before and after of using Unnested.

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.3-main.0

dev_dependencies:
  flutter_test:
    sdk: flutter
